In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest, SelectPercentile
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.feature_selection import SelectFromModel

In [ ]:
titanic = sns.load_dataset('titanic')

In [ ]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
titanic.drop(labels = ['age', 'deck'], axis = 1, inplace = True)

In [ ]:
titanic = titanic.dropna()

In [ ]:
titanic.isnull().sum()

survived       0
pclass         0
sex            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [ ]:
data = titanic[['pclass', 'sex', 'sibsp', 'parch', 'embarked', 'who', 'alone']].copy()

In [ ]:
data.head()

pclass     sex  sibsp  parch embarked    who  alone
0       3    male      1      0        S    man  False
1       1  female      1      0        C  woman  False
2       3  female      0      0        S  woman   True
3       1  female      1      0        S  woman  False
4       3    male      0      0        S    man   True

In [ ]:
data.isnull().sum()

pclass      0
sex         0
sibsp       0
parch       0
embarked    0
who         0
alone       0
dtype: int64

In [ ]:
sex = {'male': 0, 'female': 1}
data['sex'] = data['sex'].map(sex)

In [ ]:
data.head()

pclass  sex  sibsp  parch embarked    who  alone
0       3    0      1      0        S    man  False
1       1    1      1      0        C  woman  False
2       3    1      0      0        S  woman   True
3       1    1      1      0        S  woman  False
4       3    0      0      0        S    man   True

In [ ]:
ports = {'S': 0, 'C': 1, 'Q': 2}
data['embarked'] = data['embarked'].map(ports)

In [ ]:
who = {'man': 0, 'woman': 1, 'child': 2}
data['who'] = data['who'].map(who)

In [ ]:
alone = {True: 1, False: 0}
data['alone'] = data['alone'].map(alone)

In [ ]:
data.head()

pclass  sex  sibsp  parch  embarked  who  alone
0       3    0      1      0         0    0      0
1       1    1      1      0         1    1      0
2       3    1      0      0         0    1      1
3       1    1      1      0         0    1      0
4       3    0      0      0         0    0      1

In [ ]:
X = data.copy()
y = titanic['survived']

In [ ]:
X.shape, y.shape

((889, 7), (889,))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 43)

In [ ]:
sel = SelectFromModel(LinearRegression())

In [ ]:
sel.fit(X_train, y_train)

SelectFromModel(estimator=LinearRegression())

In [ ]:
sel.get_support()

array([ True,  True, False, False, False,  True, False])

In [ ]:
sel.estimator_.coef_

array([-0.13750402,  0.26606466, -0.07470416, -0.0668525 ,  0.04793674,
        0.23857799, -0.12929595])

In [ ]:
mean = np.mean(np.abs(sel.estimator_.coef_))

In [ ]:
mean

0.13727657291370784

In [ ]:
np.abs(sel.estimator_.coef_)

array([0.13750402, 0.26606466, 0.07470416, 0.0668525 , 0.04793674,
       0.23857799, 0.12929595])

In [ ]:
features = X_train.columns[sel.get_support()]
features

Index(['pclass', 'sex', 'who'], dtype='object')

In [ ]:
X_train_reg = sel.transform(X_train)
X_test_reg = sel.transform(X_test)

In [ ]:
X_test_reg.shape

(267, 3)

In [ ]:
def run_randomForest(X_train, X_test, y_train, y_test):
    clf = RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1)
    clf = clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print('Accuracy: ', accuracy_score(y_test, y_pred))

In [ ]:
%%time
run_randomForest(X_train_reg, X_test_reg, y_train, y_test)

Accuracy:  0.8239700374531835
CPU times: user 226 ms, sys: 46.6 ms, total: 272 ms
Wall time: 261 ms


In [ ]:
%%time
run_randomForest(X_train, X_test, y_train, y_test)

Accuracy:  0.8239700374531835
CPU times: user 236 ms, sys: 27.1 ms, total: 263 ms
Wall time: 245 ms


In [ ]:
X_train.shape

(622, 7)